version: '3'
services:
  frontend-app:
    container_name: frontend-app
    image: frontend-app
    restart: unless-stopped
    build: .
    ports:
      - '${PORT}:${PORT}'
    command: npm run dev
    volumes:
      - .:/opt/frontend-app
